name: ampel
channels:
  - ampelproject
  - conda-forge
dependencies:
  - python>=3.6
  - werkzeug
  - pymongo
  - fastavro
  - pytest
#  - pykafka
  - python-confluent-kafka>=0.11.4
  - sqlalchemy
  - psycopg2
  - ipython
  - extcats
  - graphitesend
  - schema
  - pip:
    - schedule
    - -e
    - /Ampel
    - git+ssh://git@github-ampel-ztfbh/robertdstein/Ampel-ZTFbh.git@ccdf4b35a27a8464b54a5013f9e9964fde382e3b

