#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

envfile=$DIR/production/$1.env

if [[ ! -e $envfile ]]; then
	echo "Configuration \"$1\" does not exist. Choose one of: ($(find $DIR/production -name '*.env' | sed 's!.*/!!' | sed 's!\.env$!!' | xargs echo))"
	exit 1
fi

if [[ "$1" == "dryrun" ]]; then
	machine=$(hostname | cut -d. -f1)
	singularity-stack rm $machine
	sleep 1
	if [[ "$machine" == "burst" ]]; then
		env $(cat $envfile | xargs echo) echo "clearing $MONGO_PATH"
		env $(cat $envfile | xargs echo) sh -c 'rm -r $MONGO_PATH/*'
	fi
	env $(cat $envfile | xargs echo) singularity-stack deploy -c $DIR/production/$machine.yml $machine
	singularity-stack list
fi

