#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

envfile=$DIR/production/$1.env

if [[ ! -e $envfile ]]; then
	echo "Configuration \"$1\" does not exist. Choose one of: ($(find $DIR/production -name '*.env' | sed 's!.*/!!' | sed 's!\.env$!!' | xargs echo))"
	exit 1
fi

if [[ $1 -eq dryrun ]]; then
	for machine in burst; do
		env $(cat $envfile | xargs echo) singularity-stack deploy -c $DIR/production/$machine.yml $machine
		echo started $machine
	done
	singularity-stack list
fi
