default:
  console:
    std_stream: stdout
    datefmt: '%Y-%m-%d '
    timefmt: '%H:%M:%S '
    level: 2048
    aggregate_interval: 1.0
    density: default
    terminator: "\n"
    log_sep: "\n"
    prefix: null
    provenance: true
    color: true
    cdate: 'cornflower_blue'
    ctime: 'light_sea_green'
    cfile: 'salmon1'
    cline: 'rosy_brown'
    clvl: 'grey53'
  db:
    level: 2048

compact:
  console:
    level: 2048
    density: compact
    log_sep: ''
  db:
    level: 2048

headerless:
  console:
    level: 2048
    density: headerless
  db:
    level: 2048

prod:
  console:
    std_stream: stderr
    level: 4096
  db:
    level: 2048

verbose:
  console:
    std_stream: stdout
    level: 1024
  db:
    level: 1024

debug:
  console:
    std_stream: stdout
    level: 512
  db:
    level: 512

silent: {}

console_quiet:
  console:
    level: 4096

console_info:
  console:
    level: 2048

console_verbose:
  console:
    level: 1024

console_debug:
  console:
    level: 512
