default:
  console:
    std_stream: stdout
    datefmt: '%Y-%m-%d '
    timefmt: '%H:%M:%S '
    level: INFO
    aggregate_interval: 1.0
    density: default
    terminator: "\n"
    log_sep: "\n"
    prefix: null
    provenance: true
    color: true
    cdate: 'cornflower_blue'
    ctime: 'light_sea_green'
    cfile: 'salmon1'
    cline: 'rosy_brown'
    clvl: 'grey53'
  db:
    level: INFO

compact:
  console:
    level: INFO
    density: compact
  db:
    level: INFO

inline:
  console:
    level: INFO
    density: inline
  db:
    level: INFO

prod:
  console:
    std_stream: stderr
    level: SHOUT
  db:
    level: INFO

verbose:
  console:
    std_stream: stdout
    level: VERBOSE
  db:
    level: VERBOSE

debug:
  console:
    std_stream: stdout
    level: DEBUG
  db:
    level: DEBUG

silent: {}

console_quiet:
  console:
    level: SHOUT

console_info:
  console:
    level: INFO

console_verbose:
  console:
    level: VERBOSE

console_debug:
  console:
    level: DEBUG
