FROM python:3.8.5

RUN apt-get update && \
    apt-get install -y bash jq && \
    pip install mypy==0.770 mypy2junit

ADD .jenkins/run_mypy.sh /bin

ADD .jenkins/Ampel-interface /Ampel-interface
RUN pip install -r /Ampel-interface/requirements.txt /Ampel-interface

ADD requirements.txt /
RUN pip install -r /requirements.txt
