FROM python:3.8.5

RUN apt-get update && \
    apt-get install -y bash jq && \
    pip install mypy==0.770 mypy2junit

ADD .jenkins/run_mypy.sh /bin

ADD .jenkins /build/.jenkins
RUN cd /build && pip install \
    .jenkins/Ampel-interface

ADD setup.py /build/setup.py
ADD ampel /build/ampel
RUN cd /build && pip install -e .[testing]

