version: '3.4'
services:
  mongo:
    image: mongo:3.6
    command: ["mongod", "--port", "$MONGO_PORT"]
    volumes:
      - $MONGO_PATH:/data/db
      - $MONGO_INITDB_PATH:/docker-entrypoint-initdb.d
    secrets:
      - mongo-root-password
      - mongo-alertprocessor-password
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
      MONGO_USER: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
  catalog:
   image: mongo:3.6
   command: ["mongod", "--port", "$CATALOG_PORT"]
   volumes:
     - $CATALOG_INITDB_PATH:/docker-entrypoint-initdb.d/
     - $CATALOG_MONGODUMP_PATH:/mnt
   ports:
     - "27018:27018"
   secrets:
     - mongo-root-password
     - catalog-read-password
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
     MONGODUMP_DIR: /mnt
     MONGO_USER: filterclient
     MONGO_PASSWORD_FILE: /run/secrets/catalog-read-password
  stats:
    image: ampel:$AMPEL_TAG
    command: ["ampel-statspublisher", "--mongo", "$MONGO_HOST:$MONGO_PORT", "--graphite", "$GRAPHITE_HOST:$GRAPHITE_PORT"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
      - /data/ampel/archive/tarballs:/ztf
    secrets:
      - mongo-alertprocessor-password
      - catalog-read-password
    environment:
      TINI_SUBREAPER: 1
      MONGO: $MONGO_HOST:$MONGO_PORT
      GRAPHITE: $GRAPHITE_HOST:$GRAPHITE_PORT
      MONGO_USER: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
      CATALOG_READ_USER: filterclient
      CATALOG_READ_USER_PASSWORD_FILE: /run/secrets/catalog-read-password
    depends_on:
      - mongo
  alertprocessor:
    image: ampel:$AMPEL_TAG
    command: ["ampel-alertprocessor", "--broker", "epyc.astro.washington.edu:9092", "--group", "$GROUP_NAME"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
      - /data/ampel/archive/tarballs:/ztf
    secrets:
      - archive-write-password
      - mongo-alertprocessor-password
    environment:
      TINI_SUBREAPER: 1
      MONGO: $MONGO_HOST:$MONGO_PORT
      GRAPHITE: $GRAPHITE_HOST:$GRAPHITE_PORT
      CATALOG: $CATALOG_HOST:$CATALOG_PORT
      ARCHIVE: $ARCHIVE_HOST:$ARCHIVE_PORT
      MONGO_USER: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
      ARCHIVE_WRITE_USER: ampel-client
      ARCHIVE_WRITE_USER_PASSWORD_FILE: /run/secrets/archive-write-password
    deploy:
      replicas: $NUM_STREAMS
      restart_policy:
          condition: any
          delay: 10s
    depends_on:
      - mongo
  t2-controller:
    image: ampel:$AMPEL_TAG
    command: ["ampel-t2", "--mongo-host", "$MONGO_HOST:$MONGO_PORT"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
    secrets:
      - mongo-alertprocessor-password
    environment:
      TINI_SUBREAPER: 1
      MONGO: $MONGO_HOST:$MONGO_PORT
      MONGO_USER: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
    deploy:
      restart_policy:
          max-attempts: 3
          condition: any
          delay: 10s
    depends_on:
      - mongo
  t3-controller:
    image: ampel:$AMPEL_TAG
    command: ["ampel-t3", "--mongo-host", "$MONGO_HOST:$MONGO_PORT"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
    secrets:
      - mongo-alertprocessor-password
    environment:
      TINI_SUBREAPER: 1
      MONGO: $MONGO_HOST:$MONGO_PORT
      MONGO_USER: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
    deploy:
      restart_policy:
          max-attempts: 3
          condition: any
          delay: 10s
    depends_on:
      - mongo

secrets:
  archive-write-password:
    file: secrets/archive-write-password.txt
  mongo-root-password:
    file: secrets/mongo-root-password.txt
  mongo-alertprocessor-password:
    file: secrets/mongo-alertprocessor-password.txt
  catalog-read-password:
    file: secrets/catalog-read-password.txt
