version: '3.4'
services:
  catalog:
   # NB: we start the catalog _first_ because it may need to use port 27017 to initialize
   image: mongo:3.6
   command: ["mongod", "--port", "$CATALOG_PORT"]
   volumes:
     - $CATALOG_PATH:/data/db
     - $CATALOG_INITDB_PATH:/docker-entrypoint-initdb.d/
     - $CATALOG_MONGODUMP_PATH:/mnt
   ports:
     - "$CATALOG_PORT:$CATALOG_PORT"
   secrets:
     - mongo-root-password
     - catalog-read-password
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
     MONGODUMP_DIR: /mnt
     MONGO_USER: filterclient
     MONGO_PASSWORD_FILE: /run/secrets/catalog-read-password
  mongo:
    image: mongo:3.6
    command: ["mongod", "--port", "$MONGO_PORT"]
    volumes:
      - $MONGO_PATH:/data/db
      - $MONGO_INITDB_PATH:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    secrets:
      - mongo-root-password
      - mongo-alertprocessor-password
      - mongo-logger-password
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
      MONGO_USER: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
      LOGGER_USER: logger
      LOGGER_PASSWORD_FILE: /run/secrets/mongo-logger-password
  stats:
    image: ampel:$AMPEL_TAG
    command: ["ampel-statspublisher"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
    secrets:
      - mongo-alertprocessor-password
      - archive-read-password
    environment:
      TINI_SUBREAPER: 1

      MONGO_HOSTNAME: $MONGO_HOST
      MONGO_PORT: $MONGO_PORT
      MONGO_LOGGER_USERNAME: logger
      MONGO_LOGGER_PASSWORD_FILE: /run/secrets/mongo-logger-password

      ARCHIVE_HOSTNAME: $ARCHIVE_HOST
      ARCHIVE_PORT: $ARCHIVE_PORT
      ARCHIVE_READER_USERNAME: ampel-readonly
      ARCHIVE_READER_PASSWORD_FILE: /run/secrets/archive-read-password
      
      GRAPHITE_HOSTNAME: $GRAPHITE_HOST
      GRAPHITE_PORT: $GRAPHITE_PORT
    deploy:
        restart_policy:
            condition: any
            delay: 10s
    depends_on:
      - mongo
      - archive
      - graphite
  alertprocessor:
    image: ampel:$AMPEL_TAG
    command: ["ampel-alertprocessor", "--broker", "epyc.astro.washington.edu:9092", "--group", "$GROUP_NAME"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
      - $CATSHTM_PATH:/catalogs/catsHTM
    secrets:
      - archive-write-password
      - mongo-alertprocessor-password
      - catalog-read-password
    environment:
      TINI_SUBREAPER: 1
      MONGO_HOSTNAME: $MONGO_HOST
      MONGO_PORT: $MONGO_PORT
      MONGO_WRITER_USERNAME: alertprocessor
      MONGO_WRITER_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
      
      GRAPHITE_HOSTNAME: $GRAPHITE_HOST
      GRAPHITE_PORT: $GRAPHITE_PORT

      ARCHIVE_HOSTNAME: $ARCHIVE_HOST
      ARCHIVE_PORT: $ARCHIVE_PORT
      ARCHIVE_WRITER_USERNAME: ampel-client
      ARCHIVE_WRITER_PASSWORD_FILE: /run/secrets/archive-write-password

      CATSHTM_PATH: /catalogs/catsHTM
      EXTCATS_HOSTNAME: $CATALOG_HOST
      EXTCATS_PORT: $CATALOG_PORT
      EXTCATS_USERNAME: filterclient
      EXTCATS_PASSWORD_FILE: /run/secrets/catalog-read-password

    deploy:
      replicas: $NUM_STREAMS
      restart_policy:
          condition: any
          delay: 10s
    depends_on:
      - mongo
      - archive
  t2-controller:
    image: ampel:$AMPEL_TAG
    command: ["ampel-t2"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
    secrets:
      - mongo-alertprocessor-password
    environment:
      TINI_SUBREAPER: 1
      MONGO_HOSTNAME: $MONGO_HOST
      MONGO_PORT: $MONGO_PORT
      MONGO_USERNAME: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
    deploy:
      restart_policy:
          max_attempts: 3
          condition: any
          delay: 10s
    depends_on:
      - mongo
  t3-controller:
    image: ampel:$AMPEL_TAG
    command: ["ampel-t3"]
    volumes:
      - type: volume
        source: $AMPEL_SRC
        target: /Ampel
    secrets:
      - mongo-alertprocessor-password
    environment:
      TINI_SUBREAPER: 1
      MONGO_HOSTNAME: $MONGO_HOST
      MONGO_PORT: $MONGO_PORT
      MONGO_USERNAME: alertprocessor
      MONGO_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
    deploy:
      restart_policy:
          max_attempts: 3
          condition: any
          delay: 10s
    depends_on:
      - mongo

secrets:
  archive-read-password:
    file: secrets/archive-read-password.txt
  archive-write-password:
    file: secrets/archive-write-password.txt
  mongo-root-password:
    file: secrets/mongo-root-password.txt
  mongo-alertprocessor-password:
    file: secrets/mongo-alertprocessor-password.txt
  mongo-logger-password:
    file: secrets/mongo-logger-password.txt
  catalog-read-password:
    file: secrets/catalog-read-password.txt
