x-ampel-env: &ampel-env
  TINI_SUBREAPER: 1
  MONGO_HOSTNAME: $MONGO_HOST
  MONGO_PORT: $MONGO_PORT
  MONGO_WRITER_USERNAME: alertprocessor
  MONGO_WRITER_PASSWORD_FILE: /run/secrets/mongo-alertprocessor-password
  MONGO_LOGGER_USERNAME: logger
  MONGO_LOGGER_PASSWORD_FILE: /run/secrets/mongo-logger-password
  
  GRAPHITE_HOSTNAME: $GRAPHITE_HOST
  GRAPHITE_PORT: $GRAPHITE_PORT

  ARCHIVE_HOSTNAME: $ARCHIVE_HOST
  ARCHIVE_PORT: $ARCHIVE_PORT
  ARCHIVE_WRITER_USERNAME: ampel-client
  ARCHIVE_WRITER_PASSWORD_FILE: /run/secrets/archive-write-password

  CATSHTM_PATH: /catalogs/catsHTM
  EXTCATS_HOSTNAME: $CATALOG_HOST
  EXTCATS_PORT: $CATALOG_PORT
  EXTCATS_READER_USERNAME: filterclient
  EXTCATS_READER_PASSWORD_FILE: /run/secrets/catalog-read-password

  SLOT: {{.Task.Slot}}

x-ampel: &ampel
  image: ampel:$AMPEL_TAG
  volumes:
    - type: volume
      source: $AMPEL_SRC
      target: /Ampel
    - $CATSHTM_PATH:/catalogs/catsHTM
  secrets:
    - archive-write-password
    - mongo-alertprocessor-password
    - mongo-logger-password
    - catalog-read-password
  environment: *ampel-env
  deploy:
    replicas: $NUM_STREAMS
  depends_on:
    - mongo
    - archive

version: '3.4'
services:
  alertprocessor-public:
    <<: *ampel
    command: ["ampel-alertprocessor", "--archive", "2018-01-01", "2018-12-31", "--public"]
  alertprocessor-private:
    <<: *ampel
    command: ["ampel-alertprocessor", "--archive", "2018-01-01", "2018-12-31", "--private"]

secrets:
  archive-read-password:
    file: secrets/archive-read-password.txt
  archive-write-password:
    file: secrets/archive-write-password.txt
  mongo-alertprocessor-password:
    file: secrets/mongo-alertprocessor-password.txt
  mongo-logger-password:
    file: secrets/mongo-logger-password.txt
  catalog-read-password:
    file: secrets/catalog-read-password.txt
